services:
  portfolio:
    image: ptrf-portfolio:latest
    container_name: portfolio

    restart: unless-stopped

    environment:
      PORT: "3000"
      WAKAPI_INTERNAL_URL: http://wakapi:3000
      ALLOWED_ORIGINS: "https://sakuspace.my.id"

    ports:
      - "3100:3000"

    networks:
      - homelab

networks:
  homelab:
    external: true
